apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mini-alpine
  name: mini-alpine
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-alpine
  template:
    metadata:
      labels:
        app: mini-alpine
    spec:
      containers:
      - image: ghcr.io/cloudoneknr/alpine:v1.0.0
        imagePullPolicy: IfNotPresent
        name: alpine-server
        command:
        - "sleep"
        - "6000"
        volumeMounts:
        - name: mini-vol
          mountPath: /app/data
          readOnly: true
      restartPolicy: Always
      imagePullSecrets:
      - name: ghcr-sec
      volumes:
      - name: mini-vol
        hostPath:
          path: /Users/nrkodari/labs/minikube/data
