jobs:
  deploy:
    name: Test AWS cmd access
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::600605052115:role/GITHUB_ACTIONS_ROLE
        aws-region: us-east-1
    - name: Test AWS CLI
      run: aws sts get-caller-identity
