name: build-docker-image
on: workflow_dispatch
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


