name: build-docker-image
on: workflow_dispatch
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: check-out
        uses: actions/checkout@v3
      - 
        name: Run Test
        run: |
          echo "${{github.sha}}"
          echo "${{github.ref}}"
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cloudoneknr/getting-started
      - 
        name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}