name: Demo One Actions
on:
  - push
jobs:
  checkout_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          
