name: AWS CLI test
on: push
jobs:
  aws-cli-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::600605052115:role/GITHUB_ACTIONS_ROLE
          aws-region: us-east-1
      - name: Install AWS CLI v2
        run:  |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
            unzip -q /tmp/awscliv2.zip -d /tmp
            rm /tmp/awscliv2.zip
            sudo /tmp/aws/install --update
            rm -rf /tmp/aws/
      - name: Install EKSCTL
        run: |
            ARCH=amd64
            PLATFORM=$(uname -s)_$ARCH            
            curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"       
            curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
            tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
            sudo mv /tmp/eksctl /usr/local/bin
      - name: test-cli
        run: |
            aws sts get-caller-identity
            eksctl version
            eksctl info
            eksctl create cluster \
              --name demo-cluster \
              --region us-east-1 \
              --zones us-east-1a,us-east-1b \
              --version 1.27 \
              --without-nodegroup \
              --asg-access \
              --external-dns-access \
              --full-ecr-access \
              --alb-ingress-access \
              --verbose 4 \
              --with-oidc
