on:
    pull_request:
      branches: [master]

env:
GITHUB_SHA: ${{ github.sha }}
GITHUB_REF: ${{ github.ref }}
IMAGE: ember-annotation
REGISTRY_HOSTNAME: 828265674650.dkr.ecr.us-east-1.amazonaws.com

jobs:
build:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Run Build Scripts for Docker image
    - name: Build
      run: |
        echo ${{ github.sha }}
        yarn build:package-json
        yarn install --production 
        yarn build:release
        docker build -t ember-annotation:${{ github.sha }} \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
        docker tag ember-annotation:${{ github.sha }} ember-annotation:latest

    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        local-image: ember-annotation:${{ github.sha }}
        image: ember-annotation:${{ github.sha }},ember-annotation:latest